<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>festival.ico</ApplicationIcon>
    <UserSecretsId>85a627a5-d338-4f12-8147-500d0cb67b49</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NLog.config" />
    <None Remove="sample.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="festival.ico" />
    <Content Include="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="sample.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="148.0.90" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.1.3" />
  </ItemGroup>

</Project>
